let candyData = [
  {
    id: "ID01",
    name: "Panditas",
    price: 35,
    desc: "Gummy bears with fruity flavors, loved by all ages.",
    img: "img/product1.avif",
  },
  {
    id: "ID02",
    name: "Mango Enchilado",
    price: 32,
    desc: "Spicy Mango: tangy, spicy, and addictive Mexican treat.",
    img: "img/product2.jpeg",
  },
  {
    id: "ID03",
    name: "Gummy Worms",
    price: 20,
    desc: "Chewy gummy worms for playful candy cravings.",
    img: "img/product3.avif",
  },
  {
    id: "ID04",
    name: "Chocolate raisins",
    price: 45,
    desc: "Sweet chocolate-covered raisins, a timeless indulgence.",
    img: "img/product4.jpeg",
  },
  {
    id: "ID05",
    name: "Ferrero",
    price: 45,
    desc: "Crunchy hazelnut a delightful, luxurious pleasure.",
    img: "img/product5.avif",
  },
  {
    id: "ID06",
    name: "Toblerone",
    price: 55,
    desc: "Iconic Swiss chocolate, triangular delight.",
    img: "img/product6.avif",
  },
  {
    id: "ID07",
    name: "Sour Patch",
    price: 15,
    desc: "Mouth-puckering delight for candy enthusiasts.",
    img: "img/product7.jpeg",
  },
  {
    id: "ID08",
    name: "Sweet Arts",
    price: 85,
    desc: "Colorful fruity candies that pop with flavor.",
    img: "img/product8.jpeg",
  },
];
