let candyData = [
  {
    id: "ID01",
    name: "Panditas",
    price: 35,
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
    img: "img/product1.avif",
  },
  {
    id: "ID02",
    name: "Mango Enchilado",
    price: 32,
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
    img: "img/product2.jpeg",
  },
  {
    id: "ID03",
    name: "Gummy Worms",
    price: 20,
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
    img: "img/product3.avif",
  },
  {
    id: "ID04",
    name: "Pasitas de Chocolate",
    price: 45,
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
    img: "img/product4.jpeg",
  },
  {
    id: "ID05",
    name: "Ferrero",
    price: 45,
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
    img: "img/product5.avif",
  },
  {
    id: "ID06",
    name: "Toblerone",
    price: 55,
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
    img: "img/product6.avif",
  },
  {
    id: "ID07",
    name: "Sour Patch",
    price: 15,
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
    img: "img/product7.jpeg",
  },
  {
    id: "ID08",
    name: "Sweet Arts",
    price: 85,
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
    img: "img/product8.jpeg",
  },
];
